name: Deploy Backend to Hugging Face

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.5'

    - name: Install Hugging Face CLI
      run: pip install huggingface_hub

    - name: Copy Backend Files to Hugging Face Space
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: |
        hf_repo="Zok213/AI-Service"
        backend_folder="backend"
        
        cd $backend_folder
        huggingface-cli login --token $HF_API_TOKEN
        huggingface-cli repo create $hf_repo --space_type=gradio --yes --private || true
        huggingface-cli repo upload . --repo-id $hf_repo --token $HF_API_TOKEN --create-pr
